name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        version: ['5.12.8', '5.15.0']
    steps:
      - uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Install libxkbcommon-x11-0
        run: sudo apt-get install libxkbcommon-x11-0
        if: contains(matrix.os, 'ubuntu')

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/Qt-${{ runner.os }}-${{ matrix.version }}
          key: ${{ runner.os }}-QtCache-${{ matrix.version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.version }}
          dir: ${{ github.workspace }}/Qt-${{ runner.os }}-${{ matrix.version }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure QOlm
        run: |
          mkdir -p build
          cmake -DQOLM_ENABLE_TESTS=ON -DQOLM_ENABLE_EXAMPLES=ON -DCMAKE_BUILD_TYPE="Release" -B build -S .
        shell: bash

      - name: Build QOlm
        run: cmake --build build --target "QOlm" --config "Release"

      - name: Build Examples
        run: cmake --build build --target "QOlm_Example" --config "Release"

      - name: Build Cpp Tests
        run: cmake --build build --target "QOlm_Tests" --config "Release"

      - name: Build Qml Tests
        run: cmake --build build --target "QOlm_TestsQml" --config "Release"

      - name: Run unit tests
        run: |
          export QT_DEBUG_PLUGINS=1
          cd build
          ctest --build-config "Release" --progress --verbose